config/routes.rb
Try2::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :songs
  root :to => "songs#index"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user_id, :provider, :uid
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :title, :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  
 def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token['extra']['user_hash']
    if user = User.find_by_email(data["email"])
      user
    else # Create an user with a stub password. 
      user = User.create!(:email => data["email"], :password => Devise.friendly_token[0,20]) 
    end
    auth       = user.authentications.find_or_create_by_provider_and_uid(access_token['provider'], access_token['uid'])
    auth.token = access_token['credentials']['token']
    auth.save!
    user
    
 end 
 
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"]
        user.email = data["email"]
      end
    end
  end
  
  def facebook
    @fb_user ||= FbGraph::User.me(self.authentications.find_by_provider('facebook').token)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    #current_user.facebook.feed!(:message => 'Hello, Facebook!', :name => 'My Rails 3 App with Omniauth, Devise and FB_graph') if current_user
    @authentications = current_user.authentications if current_user
  end
  
  
  def destroy
    if current_user
        @authentication = current_user.authentications.find(params[:id]) 
        @authentication.destroy
        flash[:notice] = "Successfully destroyed authentication."
    end
    redirect_to authentications_url
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end
  
  def show
    @song = Song.find(params[:id])
  end
  
  def new
    @song = Song.new
  end
  
  def create
    @song = Song.new(params[:song])
    if @song.save
      flash[:notice] = "Successfully created song."
      current_user.facebook.feed!(:message => "Dodales utwor: #{@song.artist} - #{@song.title}", :name => 'Task 10') if current_user
      flash[:notice] += "Published on wall" if current_user
      redirect_to songs_path
    else
      render :action => 'new'
    end
  end
  
  def edit
    @song = Song.find(params[:id])
  end
  
  def update
    @song = Song.find(params[:id])
    if @song.update_attributes(params[:song])
      flash[:notice] = "Successfully updated song."
      redirect_to @song
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    flash[:notice] = "Successfully destroyed song."
    redirect_to songs_url
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    omniauth = env["omniauth.auth"]
    @user = User.find_for_facebook_oauth(omniauth, current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      #@user.authentications.find_or_create_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:error]  = I18n.t "devise.omniauth_callbacks.failure", :kind => "Facebook", :reason => "reason"
      flash[:error] += "Try again."
      redirect_to root_path
      #session["devise.facebook_data"] = env["omniauth.auth"]
      #redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/authentications/index.html.erb
<% title "Authentications" %>

<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
  </tr>
  <% for authentication in @authentications %>
    <tr>
      <td><%= authentication.user_id %></td>
      <td><%= authentication.provider %></td>
      <td><%= authentication.uid %></td>
      <td><%= link_to "Destroy", authentication, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      #user_nav
        - if user_signed_in?
          Signed in as 
          = current_user.email
          Not you?
          = link_to "Sign out", destroy_user_session_path
    
        - else
          = link_to "Sign up", new_user_registration_path
          or
          = link_to "Sign in", new_user_session_path
          %br
          = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

app/views/songs/_form.html.haml
- form_for @song do |f|
  = f.error_messages
  %p
    = f.label :title
    %br
    = f.text_field :title
  %p
    = f.label :artist
    %br
    = f.text_field :artist
  %p
    = f.submit

app/views/songs/edit.html.haml
- title "Edit Song"

= render 'form'

%p
  = link_to "Show", song_path(@song)
  |
  = link_to "View All", songs_path

app/views/songs/index.html.haml
- title "Songs"
%br
Informacja o dodaniu utworu będzie opublikowana na tablicy twojego facebooka
%table
  %tr
    %th Title
    %th Artist
  - for song in @songs
    %tr
      %td= song.title
      %td= song.artist
      %td= link_to 'Show', song
      %td= link_to 'Edit', edit_song_path(song)
      %td= link_to 'Destroy', song, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Song", new_song_path

app/views/songs/new.html.haml
- title "New Song"

= render 'form'

%p= link_to "Back to List", songs_path

app/views/songs/show.html.haml
- title "Song"

%p
  %strong Title:
  = @song.title
%p
  %strong Artist:
  = @song.artist

%p
  = link_to "Edit", edit_song_path(@song)
  |
  = link_to "Destroy", @song, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", songs_path